/*--------------------------------------------------
在提交该代码前，下面的选项语句应放置在
数据步之前。
--------------------------------------------------*/
options VALIDMEMNAME=EXTEND VALIDVARNAME=ANY;

/*------------------------------------------
生成的 SAS 评分代码
 日期   : 09Apr2019:02:09:07
 语言/区域: zh_CN
 模型类型 : 决策树
 区间型变量: Weight(重量)
 区间型变量: Height(高度)
 分类变量 : _va_response_41(吸烟状况)
 响应变量 : _va_response_41(吸烟状况)
 ------------------------------------------*/

/* 临时计算列 */

/*---------------------------------------------------------
SAS Code Generated by LASR Analytic Server for Decision Tree
  Date              : 2019年04月09日 02时09分07秒
  Locale            : zh_CN
  Response variable : _va_response_41
  Number of nodes   : 19
  -------------------------------------------------------*/

/*------------------------------------------*/
/*Temporary computed columns                */
length _va_response_41 $17;
_va_response_41='Smoking_Status'n;;
;
/*------------------------------------------*/
length _strfmt_ $32;
drop _strfmt_;
_strfmt_ = ' ';
array _tlevname_0_1554790147283_{6} $17  ( '                 ' 
	'                 ' 
	'非吸烟者' 
	'光（1-5）' 
	'                 ' 
	'重磅（16-25）');
_node_id_ =  0;
_new_id_  = -1;
nextnode_0:

if _node_id_ eq 0 then
	do;
		_numval_ = Height;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 65.25 and _numval_ lt 66.5) or (_numval_ ge 
			66.5 and _numval_ lt 67.75) or (_numval_ ge 
			67.75 and _numval_ lt 69) or (_numval_ ge 
			69 and _numval_ lt 70.25) or (_numval_ ge 
			70.25 and _numval_ lt 71.5) or (_numval_ ge 
			71.5 and _numval_ lt 72.75) or (_numval_ ge 
			72.75 and _numval_ lt 74) or (_numval_ ge 
			74 and _numval_ lt 75.25) or (_numval_ ge 
			75.25 and _numval_ lt 76.5) then
			do;
				_new_id_ = 1;
			end;
		else if (_numval_ ge 51.5 and _numval_ lt 52.75) or (_numval_ ge 
			52.75 and _numval_ lt 54) or (_numval_ ge 
			54 and _numval_ lt 55.25) or (_numval_ ge 
			55.25 and _numval_ lt 56.5) or (_numval_ ge 
			56.5 and _numval_ lt 57.75) or (_numval_ ge 
			57.75 and _numval_ lt 59) or (_numval_ ge 
			59 and _numval_ lt 60.25) or (_numval_ ge 
			60.25 and _numval_ lt 61.5) or (_numval_ ge 
			61.5 and _numval_ lt 62.75) or (_numval_ ge 
			62.75 and _numval_ lt 64) or (_numval_ ge 
			64 and _numval_ lt 65.25) then
			do;
				_new_id_ = 2;
			end;
		else if (_numval_ lt 51.5) then
			do;
				_new_id_ = 2;
			end;
		else if (_numval_ ge 76.5) then
			do;
				_new_id_ = 1;
			end;
		else
			do;
				_new_id_ = 2;
			end;
	end;
else if _node_id_ eq 1 then
	do;
		_numval_ = Weight;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 148.55 and _numval_ lt 160.2) or (_numval_ ge 
			160.2 and _numval_ lt 171.85) or (_numval_ ge 
			171.85 and _numval_ lt 183.5) or (_numval_ ge 
			183.5 and _numval_ lt 195.15) or (_numval_ ge 
			195.15 and _numval_ lt 206.8) or (_numval_ ge 
			206.8 and _numval_ lt 218.45) or (_numval_ ge 
			218.45 and _numval_ lt 230.1) or (_numval_ ge 
			230.1 and _numval_ lt 241.75) or (_numval_ ge 
			241.75 and _numval_ lt 253.4) or (_numval_ ge 
			253.4 and _numval_ lt 265.05) or (_numval_ ge 
			265.05 and _numval_ lt 276.7) or (_numval_ ge 
			276.7 and _numval_ lt 288.35) or (_numval_ ge 
			288.35 and _numval_ lt 300) then
			do;
				_new_id_ = 3;
			end;
		else if (_numval_ ge 67 and _numval_ lt 78.65) or (_numval_ ge 
			78.65 and _numval_ lt 90.3) or (_numval_ ge 
			90.3 and _numval_ lt 101.95) or (_numval_ ge 
			101.95 and _numval_ lt 113.6) or (_numval_ ge 
			113.6 and _numval_ lt 125.25) or (_numval_ ge 
			125.25 and _numval_ lt 136.9) or (_numval_ ge 
			136.9 and _numval_ lt 148.55) then
			do;
				_new_id_ = 4;
			end;
		else if (_numval_ lt 67) then
			do;
				_new_id_ = 4;
			end;
		else if (_numval_ ge 300) then
			do;
				_new_id_ = 3;
			end;
		else
			do;
				_new_id_ = 3;
			end;
	end;
else if _node_id_ eq 2 then
	do;
		_leaf_id_ = 2;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.56757690978223;
	end;
else if _node_id_ eq 3 then
	do;
		_numval_ = Height;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 70.25 and _numval_ lt 71.5) or (_numval_ ge 
			71.5 and _numval_ lt 72.75) or (_numval_ ge 
			72.75 and _numval_ lt 74) or (_numval_ ge 
			74 and _numval_ lt 75.25) or (_numval_ ge 
			75.25 and _numval_ lt 76.5) then
			do;
				_new_id_ = 5;
			end;
		else if (_numval_ ge 51.5 and _numval_ lt 52.75) or (_numval_ ge 
			52.75 and _numval_ lt 54) or (_numval_ ge 
			54 and _numval_ lt 55.25) or (_numval_ ge 
			55.25 and _numval_ lt 56.5) or (_numval_ ge 
			56.5 and _numval_ lt 57.75) or (_numval_ ge 
			57.75 and _numval_ lt 59) or (_numval_ ge 
			59 and _numval_ lt 60.25) or (_numval_ ge 
			60.25 and _numval_ lt 61.5) or (_numval_ ge 
			61.5 and _numval_ lt 62.75) or (_numval_ ge 
			62.75 and _numval_ lt 64) or (_numval_ ge 
			64 and _numval_ lt 65.25) or (_numval_ ge 
			65.25 and _numval_ lt 66.5) or (_numval_ ge 
			66.5 and _numval_ lt 67.75) or (_numval_ ge 
			67.75 and _numval_ lt 69) or (_numval_ ge 
			69 and _numval_ lt 70.25) then
			do;
				_new_id_ = 6;
			end;
		else if (_numval_ lt 51.5) then
			do;
				_new_id_ = 6;
			end;
		else if (_numval_ ge 76.5) then
			do;
				_new_id_ = 5;
			end;
		else
			do;
				_new_id_ = 6;
			end;
	end;
else if _node_id_ eq 4 then
	do;
		_numval_ = Height;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 66.5 and _numval_ lt 67.75) or (_numval_ ge 
			67.75 and _numval_ lt 69) or (_numval_ ge 
			69 and _numval_ lt 70.25) or (_numval_ ge 
			70.25 and _numval_ lt 71.5) or (_numval_ ge 
			71.5 and _numval_ lt 72.75) or (_numval_ ge 
			72.75 and _numval_ lt 74) or (_numval_ ge 
			74 and _numval_ lt 75.25) or (_numval_ ge 
			75.25 and _numval_ lt 76.5) then
			do;
				_new_id_ = 7;
			end;
		else if (_numval_ ge 51.5 and _numval_ lt 52.75) or (_numval_ ge 
			52.75 and _numval_ lt 54) or (_numval_ ge 
			54 and _numval_ lt 55.25) or (_numval_ ge 
			55.25 and _numval_ lt 56.5) or (_numval_ ge 
			56.5 and _numval_ lt 57.75) or (_numval_ ge 
			57.75 and _numval_ lt 59) or (_numval_ ge 
			59 and _numval_ lt 60.25) or (_numval_ ge 
			60.25 and _numval_ lt 61.5) or (_numval_ ge 
			61.5 and _numval_ lt 62.75) or (_numval_ ge 
			62.75 and _numval_ lt 64) or (_numval_ ge 
			64 and _numval_ lt 65.25) or (_numval_ ge 
			65.25 and _numval_ lt 66.5) then
			do;
				_new_id_ = 8;
			end;
		else if (_numval_ lt 51.5) then
			do;
				_new_id_ = 8;
			end;
		else if (_numval_ ge 76.5) then
			do;
				_new_id_ = 7;
			end;
		else
			do;
				_new_id_ = 7;
			end;
	end;
else if _node_id_ eq 5 then
	do;
		_numval_ = Weight;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 171.85 and _numval_ lt 183.5) or (_numval_ ge 
			183.5 and _numval_ lt 195.15) or (_numval_ ge 
			195.15 and _numval_ lt 206.8) or (_numval_ ge 
			206.8 and _numval_ lt 218.45) or (_numval_ ge 
			218.45 and _numval_ lt 230.1) or (_numval_ ge 
			230.1 and _numval_ lt 241.75) or (_numval_ ge 
			241.75 and _numval_ lt 253.4) or (_numval_ ge 
			253.4 and _numval_ lt 265.05) or (_numval_ ge 
			265.05 and _numval_ lt 276.7) or (_numval_ ge 
			276.7 and _numval_ lt 288.35) or (_numval_ ge 
			288.35 and _numval_ lt 300) then
			do;
				_new_id_ = 9;
			end;
		else if (_numval_ ge 67 and _numval_ lt 78.65) or (_numval_ ge 
			78.65 and _numval_ lt 90.3) or (_numval_ ge 
			90.3 and _numval_ lt 101.95) or (_numval_ ge 
			101.95 and _numval_ lt 113.6) or (_numval_ ge 
			113.6 and _numval_ lt 125.25) or (_numval_ ge 
			125.25 and _numval_ lt 136.9) or (_numval_ ge 
			136.9 and _numval_ lt 148.55) or (_numval_ ge 
			148.55 and _numval_ lt 160.2) or (_numval_ ge 
			160.2 and _numval_ lt 171.85) then
			do;
				_new_id_ = 10;
			end;
		else if (_numval_ lt 67) then
			do;
				_new_id_ = 10;
			end;
		else if (_numval_ ge 300) then
			do;
				_new_id_ = 9;
			end;
		else
			do;
				_new_id_ = 9;
			end;
	end;
else if _node_id_ eq 6 then
	do;
		_numval_ = Weight;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 160.2 and _numval_ lt 171.85) or (_numval_ ge 
			171.85 and _numval_ lt 183.5) or (_numval_ ge 
			183.5 and _numval_ lt 195.15) or (_numval_ ge 
			195.15 and _numval_ lt 206.8) or (_numval_ ge 
			206.8 and _numval_ lt 218.45) or (_numval_ ge 
			218.45 and _numval_ lt 230.1) or (_numval_ ge 
			230.1 and _numval_ lt 241.75) or (_numval_ ge 
			241.75 and _numval_ lt 253.4) or (_numval_ ge 
			253.4 and _numval_ lt 265.05) or (_numval_ ge 
			265.05 and _numval_ lt 276.7) or (_numval_ ge 
			276.7 and _numval_ lt 288.35) or (_numval_ ge 
			288.35 and _numval_ lt 300) then
			do;
				_new_id_ = 11;
			end;
		else if (_numval_ ge 67 and _numval_ lt 78.65) or (_numval_ ge 
			78.65 and _numval_ lt 90.3) or (_numval_ ge 
			90.3 and _numval_ lt 101.95) or (_numval_ ge 
			101.95 and _numval_ lt 113.6) or (_numval_ ge 
			113.6 and _numval_ lt 125.25) or (_numval_ ge 
			125.25 and _numval_ lt 136.9) or (_numval_ ge 
			136.9 and _numval_ lt 148.55) or (_numval_ ge 
			148.55 and _numval_ lt 160.2) then
			do;
				_new_id_ = 12;
			end;
		else if (_numval_ lt 67) then
			do;
				_new_id_ = 12;
			end;
		else if (_numval_ ge 300) then
			do;
				_new_id_ = 11;
			end;
		else
			do;
				_new_id_ = 11;
			end;
	end;
else if _node_id_ eq 7 then
	do;
		_leaf_id_ = 7;
		_new_id_ = -1;
		_dt_pred_lev_ = 5;
		_dt_pred_prob_ =     0.30815709969788;
	end;
else if _node_id_ eq 8 then
	do;
		_numval_ = Weight;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 136.9 and _numval_ lt 148.55) or (_numval_ ge 
			148.55 and _numval_ lt 160.2) or (_numval_ ge 
			160.2 and _numval_ lt 171.85) or (_numval_ ge 
			171.85 and _numval_ lt 183.5) or (_numval_ ge 
			183.5 and _numval_ lt 195.15) or (_numval_ ge 
			195.15 and _numval_ lt 206.8) or (_numval_ ge 
			206.8 and _numval_ lt 218.45) or (_numval_ ge 
			218.45 and _numval_ lt 230.1) or (_numval_ ge 
			230.1 and _numval_ lt 241.75) or (_numval_ ge 
			241.75 and _numval_ lt 253.4) or (_numval_ ge 
			253.4 and _numval_ lt 265.05) or (_numval_ ge 
			265.05 and _numval_ lt 276.7) or (_numval_ ge 
			276.7 and _numval_ lt 288.35) or (_numval_ ge 
			288.35 and _numval_ lt 300) then
			do;
				_new_id_ = 13;
			end;
		else if (_numval_ ge 67 and _numval_ lt 78.65) or (_numval_ ge 
			78.65 and _numval_ lt 90.3) or (_numval_ ge 
			90.3 and _numval_ lt 101.95) or (_numval_ ge 
			101.95 and _numval_ lt 113.6) or (_numval_ ge 
			113.6 and _numval_ lt 125.25) or (_numval_ ge 
			125.25 and _numval_ lt 136.9) then
			do;
				_new_id_ = 14;
			end;
		else if (_numval_ lt 67) then
			do;
				_new_id_ = 14;
			end;
		else if (_numval_ ge 300) then
			do;
				_new_id_ = 13;
			end;
		else
			do;
				_new_id_ = 14;
			end;
	end;
else if _node_id_ eq 9 then
	do;
		_leaf_id_ = 9;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.45348837209302;
	end;
else if _node_id_ eq 10 then
	do;
		_leaf_id_ = 10;
		_new_id_ = -1;
		_dt_pred_lev_ = 5;
		_dt_pred_prob_ =      0.5045871559633;
	end;
else if _node_id_ eq 11 then
	do;
		_leaf_id_ = 11;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.40864440078585;
	end;
else if _node_id_ eq 12 then
	do;
		_numval_ = Height;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 66.5 and _numval_ lt 67.75) or (_numval_ ge 
			67.75 and _numval_ lt 69) or (_numval_ ge 
			69 and _numval_ lt 70.25) or (_numval_ ge 
			70.25 and _numval_ lt 71.5) or (_numval_ ge 
			71.5 and _numval_ lt 72.75) or (_numval_ ge 
			72.75 and _numval_ lt 74) or (_numval_ ge 
			74 and _numval_ lt 75.25) or (_numval_ ge 
			75.25 and _numval_ lt 76.5) then
			do;
				_new_id_ = 15;
			end;
		else if (_numval_ ge 51.5 and _numval_ lt 52.75) or (_numval_ ge 
			52.75 and _numval_ lt 54) or (_numval_ ge 
			54 and _numval_ lt 55.25) or (_numval_ ge 
			55.25 and _numval_ lt 56.5) or (_numval_ ge 
			56.5 and _numval_ lt 57.75) or (_numval_ ge 
			57.75 and _numval_ lt 59) or (_numval_ ge 
			59 and _numval_ lt 60.25) or (_numval_ ge 
			60.25 and _numval_ lt 61.5) or (_numval_ ge 
			61.5 and _numval_ lt 62.75) or (_numval_ ge 
			62.75 and _numval_ lt 64) or (_numval_ ge 
			64 and _numval_ lt 65.25) or (_numval_ ge 
			65.25 and _numval_ lt 66.5) then
			do;
				_new_id_ = 16;
			end;
		else if (_numval_ lt 51.5) then
			do;
				_new_id_ = 16;
			end;
		else if (_numval_ ge 76.5) then
			do;
				_new_id_ = 15;
			end;
		else
			do;
				_new_id_ = 15;
			end;
	end;
else if _node_id_ eq 13 then
	do;
		_leaf_id_ = 13;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.45762711864406;
	end;
else if _node_id_ eq 14 then
	do;
		_numval_ = Weight;

		if missing(_numval_) then
			do;
				_numval_ = -1.7976931348623E308;
			end;

		if (_numval_ ge 113.6 and _numval_ lt 125.25) or (_numval_ ge 
			125.25 and _numval_ lt 136.9) or (_numval_ ge 
			136.9 and _numval_ lt 148.55) or (_numval_ ge 
			148.55 and _numval_ lt 160.2) or (_numval_ ge 
			160.2 and _numval_ lt 171.85) or (_numval_ ge 
			171.85 and _numval_ lt 183.5) or (_numval_ ge 
			183.5 and _numval_ lt 195.15) or (_numval_ ge 
			195.15 and _numval_ lt 206.8) or (_numval_ ge 
			206.8 and _numval_ lt 218.45) or (_numval_ ge 
			218.45 and _numval_ lt 230.1) or (_numval_ ge 
			230.1 and _numval_ lt 241.75) or (_numval_ ge 
			241.75 and _numval_ lt 253.4) or (_numval_ ge 
			253.4 and _numval_ lt 265.05) or (_numval_ ge 
			265.05 and _numval_ lt 276.7) or (_numval_ ge 
			276.7 and _numval_ lt 288.35) or (_numval_ ge 
			288.35 and _numval_ lt 300) then
			do;
				_new_id_ = 17;
			end;
		else if (_numval_ ge 67 and _numval_ lt 78.65) or (_numval_ ge 
			78.65 and _numval_ lt 90.3) or (_numval_ ge 
			90.3 and _numval_ lt 101.95) or (_numval_ ge 
			101.95 and _numval_ lt 113.6) then
			do;
				_new_id_ = 18;
			end;
		else if (_numval_ lt 67) then
			do;
				_new_id_ = 18;
			end;
		else if (_numval_ ge 300) then
			do;
				_new_id_ = 17;
			end;
		else
			do;
				_new_id_ = 17;
			end;
	end;
else if _node_id_ eq 15 then
	do;
		_leaf_id_ = 15;
		_new_id_ = -1;
		_dt_pred_lev_ = 5;
		_dt_pred_prob_ =      0.3347280334728;
	end;
else if _node_id_ eq 16 then
	do;
		_leaf_id_ = 16;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.41964285714285;
	end;
else if _node_id_ eq 17 then
	do;
		_leaf_id_ = 17;
		_new_id_ = -1;
		_dt_pred_lev_ = 2;
		_dt_pred_prob_ =     0.33057851239669;
	end;
else if _node_id_ eq 18 then
	do;
		_leaf_id_ = 18;
		_new_id_ = -1;
		_dt_pred_lev_ = 3;
		_dt_pred_prob_ =                  0.4;
	end;

if _new_id_ >= 0 then
	do;
		_node_id_ = _new_id_;
		goto nextnode_0;
	end;

DT__va_response_41 = _tlevname_0_1554790147283_{_dt_pred_lev_+1};
drop _numval_;
drop _node_id_;
drop _new_id_;   /*------------------------------------------*/
drop _va_: _local_id_: '_va_response_41'n 'DT__va_response_41'n '_leaf_id_'n;
length 'DT__va_response_41_41_2'n $17;
'DT__va_response_41_41_2'n='DT__va_response_41'n;
'_leaf_id__41_2'n='_leaf_id_'n;
/*------------------------------------------*/